title: 师小师の博客
# 主页网站副标题
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (循环打字)
  loop: false
  # source 调用第三方服务
  # source: false 关闭调用
  # source: 1  调用一言网的一句话（简体） https://hitokoto.cn/
  # source: 2  调用一句网（简体） http://yijuzhan.com/
  # source: 3  调用今日诗词（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: 1
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
   - 须知少时拏云志，曾许人间第一流。
   - 昨夜星辰昨夜风，画楼西畔桂堂东。
   - 夫天地者，万物之逆旅也；光阴者，百代之过客也。
   - 自信人生二百年，会当水击三千里。
description: 学习 记录 分享
keywords:
author: 师小师
language: zh-CN
timezone: Asia/Shanghai


abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
  
# URL 连接标题
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://shijinying.top/
# 文章永久链接的形成模版。每一篇文章都有唯一的url
# permalink: :year/:month/:day/:title/
permalink: posts/:abbrlink.html
#文章永久链接中，各部分的默认值
permalink_defaults:
  lang: en
pretty_urls:
  # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_index: true
  # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
  trailing_html: true



# Directory
# 资源文件夹，这个文件夹用来存放写的博客内容
source_dir: source
# 公共文件夹，这个文件夹用于存放生成的站点文件
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
 # 分类文件夹
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
# 默认新建的文件名
new_post_name: :title.md
# 新建文档的默认布局
default_layout: post
# 是否要把标题中的首字符大写
titlecase: false
external_link:
  # 是否要在新开tab中打开链接
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
# 加载静态资源
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:


# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/sjy-smile/sjy-smile.github.io.git
  branch: master
  

# 404页面设置（内置）
error_404:
  enable: true
  subtitle: "页面沒有找到"
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png